### ISSUE TITLE
Re: The Puppet Race: On your mark

### ISSUE THREAD

**Issue by PeterMortensen** [jericson/jericson.github.io#13]
I suggest linking more directly to the next blog post in the five-part series (forward linking). There is a link, but it could be more obvious ("get an account" may be perceived as something else).

*[The Puppet Race](https://jlericson.com/2017/07/26/race_to_1k_1.html)*

More generally, I think a link (to the next page in the series) at the end of each page would be expected, e.g. near *"Next time"*.

**Comment by jericson** [comment]
That's a really good suggestion. I've added a little forward linking at the end of each article. "Next time" is a great link text too.

Thanks!
